version: '3'

services:
  registry:
    image: brewmon-registry
    build:
      dockerfile: Dockerfile
      context: ./
    command: node app.js
    ports:
      - 3000:4000
    environment:
      PORT: 4000
